services:
  deadsea-scrolls-dev:
    image: deadsea-scrolls-dev
    container_name: deadsea-scrolls-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /deadsea-scrolls
    volumes:
      - ..:/deadsea-scrolls:cached
    tty: true
