services:
  dead-sea-scrolls-dev:
    image: dead-sea-scrolls-dev
    container_name: dead-sea-scrolls-dev
    build:
      context: ../.
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /dead-sea-scrolls
    volumes:
      - ..:/dead-sea-scrolls:cached
    tty: true
